#include "game.h"

//CAMBIAR LA CONDICION DEL IF, SI es mayor/menor que cero QUE REBOTE A LAS PADDLES

//MODIFICAR EL LUGAR DE LAS CARPETAS

//TAL VEZ MODIFICAR LAS VARIABLES DE MENU PARA QUE SEAN STRUCTS

//AGREGAR MODO DE JUEGO VS BOT, PODES PONER UNA BOTONERA COMO LOS COLORES PERO PARA VS PLAYER O VS BOT,
//LO MISMO PODES HACER PARA LA RESOLUCION DE PANTALLA AHHHHHHHHHHHHHHHHHHHHHHHH

void main()
{
	catPong::executeGame();
}

