#include "game.h"

//CAMBIAR LA CONDICION DEL IF, SI es mayor/menor que cero QUE REBOTE. PODRIA APLICARSE LO MISMO PARA LAS PADDLES

//MODIFICAR EL LUGAR DE LAS CARPETAS

//TAL VEZ MODIFICAR LAS VARIABLES DE MENU PARA QUE SEAN STRUCTS

//MODIFICAR TODO PARA QUE SE PUEDA CAMBIAR DE TAMAÑO LA PANTALLA

using namespace catPong;
void main()
{
	executeGame();
}

