#include "game.h"

//PONER COSAS QUE SE REPITAN EN FUNCIONES CON PARAMETROS

//MODIFICAR EL LUGAR DE LAS CARPETAS			-----

//TAL VEZ MODIFICAR LAS VARIABLES DE MENU PARA QUE SEAN STRUCTS

//QUITAR MAYUS A TODAS LAS DEFINICIONES DE STRUCS? O SEA POR EJ NO a Rectangle sino a PlayButton

//HACER QUE LA ENDING SCREEN SEA CON EL MOUSE, CONSISTENCIA!							-----

void main(){
	catPong::executeGame();
}